### register
POST https://fetch-api-production.up.railway.app/dashboard
Content-Type: application/json

{
    "email":"aajao@linksmfb.com",
    "password":"P@ssw)rd"
}

### cronRepaymentService
GET https://fetch-api-production.up.railway.app/dashboard/repaymentJob
Content-Type: application/json


### cronRepaymentService
GET https://fetch-api-production.up.railway.app/dashboard/email
Content-Type: application/json


### add token
GET https://fetch-api-production.up.railway.app/dashboard/test
Content-Type: application/json
