### register
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email":"lastesttest@gmail.com",
    "password":"password"
}

### get all users
GET http://localhost:3000/user
Content-Type: application/json


### block user
POST http://localhost:3000/user/active
Content-Type: application/json 

{
    "email":"lastesttest@gmail.com",
    "status":"active"
}

### login
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "email":"lastesttest@gmail.com",
    "password":"newpassword"
}

### reset password
POST http://localhost:3000/userß/resetpassword
Content-Type: application/json 

{
    "email":"lastesttest@gmail.com",
    "password":"newpassword"
}