### register
POST https://fetch-api-production.up.railway.app/dashboard
Content-Type: application/json

{
    "email":"wadeyemi@linksmfb.com",
    "password":"password"
}

### cronRepaymentService
GET https://fetch-api-production.up.railway.app/dashboard/repaymentJob
Content-Type: application/json