### register
POST https://fetch-api-production.up.railway.app/users/register
Content-Type: application/json

{
    "email":"wadeyemi@linksmfb.com",
    "password":"password"
}

### get all users
GET http://localhost:3000/users
Content-Type: application/json


### block user
POST http://localhost:3000/users/active
Content-Type: application/json 

{
    "email":"lastesttest@gmail.com",
    "status":"active"
}

### login
POST http://localhost:3000/users/login
Content-Type: application/json 

{
    "email":"mau@gmail.com",
    "password":"password"
}

### reset password
POST http://localhost:3000/users/resetpassword
Content-Type: application/json 

{
    "email":"lastesttest@gmail.com",
    "password":"newpassword"
}