### add token
POST https://fetch-api-production.up.railway.app/tokens/create
Content-Type: application/json

{
    "email":"23232re2323we",
    "token":"",
    "tokenExpiry":"",
    "data":"password"
}

### get token data
GET http://localhost:3000/tokens/23232re2323we
Content-Type: application/json
